version: '3.3'
services:
  post_db:
    container_name: post-db
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}

  ui:
    container_name: ui
    image: ${USERNAME}/ui:${UIVERSION}
    ports:
      - ${REDDITPORT}:9292/tcp
    networks:
      front_net:
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}

  post:
    container_name: post
    image: ${USERNAME}/post:${POSTVERSION}
    networks:
      back_net:
        aliases:
          - post
      front_net:
        aliases:
          - post
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}

  comment:
    container_name: comment
    image: ${USERNAME}/comment:${COMMENTVERSION}
    networks:
      back_net:
        aliases:
          - comment
      front_net:
        aliases:
          - comment
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}

  prometheus:
    image: ${USERNAME}/prometheus
    networks:
      - back_net
      - front_net
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command:
      # Передаем доп параметры в командной строке
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d' # Задаем время хранения метрик в 1 день

  node-exporter:
    image: prom/node-exporter:v0.15.2
    user: root
    networks:
      - back_net
      - front_net
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'

volumes:
  post_db:
  prometheus_data:

networks:
  back_net:
    ipam:
      config:
        - subnet: 10.0.1.0/24
  front_net:
    ipam:
      config:
        - subnet: 10.0.2.0/24
